/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.29
 * Generated at: 2024-10-20 08:54:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class catalogpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Vehicle Parts Catalog</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background-color: #f8f9fa; /* Light background like profile page */\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            margin: 40px auto;\r\n");
      out.write("            background-color: #ffffff; /* White background for the container */\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.1); /* Softer shadow */\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #333; /* Dark text color for the title */\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .catalog {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("        .item {\r\n");
      out.write("            width: 23%;\r\n");
      out.write("            background-color: #ffffff; /* White background for each item */\r\n");
      out.write("            color: #333; /* Dark text color */\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.1); /* Subtle shadow */\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("        }\r\n");
      out.write("        .item:hover {\r\n");
      out.write("            transform: translateY(-5px); /* Slight hover effect */\r\n");
      out.write("            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.15); /* Deeper shadow on hover */\r\n");
      out.write("        }\r\n");
      out.write("        .item img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 180px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-bottom: 2px solid #eee;\r\n");
      out.write("        }\r\n");
      out.write("        .item h3 {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin: 15px 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .item p {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("            color: #555; /* Slightly lighter text for descriptions */\r\n");
      out.write("        }\r\n");
      out.write("        .price {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            color: #28a745; /* Green color for price */\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 10px 16px;\r\n");
      out.write("            background-color: #007bff; /* Blue color for buttons */\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: background-color 0.3s, transform 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background-color: #0056b3; /* Darker blue on hover */\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1>Vehicle Parts Catalog</h1>\r\n");
      out.write("    <div class=\"catalog\">\r\n");
      out.write("        <!-- First Row -->\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"images/A.jpg\" alt=\"Engine Oil\">\r\n");
      out.write("            <h3>Engine 123</h3>\r\n");
      out.write("            <p>Part No: 12883945375</p>\r\n");
      out.write("            <p class=\"price\">$25.99</p>\r\n");
      out.write("            <a href=\"singalpoduct page.jsp\"><button class=\"btn\">veiw</button></a> \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"images/B.jpeg\" alt=\"Brake Pad\">\r\n");
      out.write("            <h3>Engine 982</h3>\r\n");
      out.write("            <p>Part No: 12198377722</p>\r\n");
      out.write("            <p class=\"price\">$45.00</p>\r\n");
      out.write("           <button class=\"btn\">veiw</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"images/C.jpeg\" alt=\"Air Filter\">\r\n");
      out.write("            <h3>Engine 654</h3>\r\n");
      out.write("            <p>Part No: 14158599225</p>\r\n");
      out.write("            <p class=\"price\">$15.50</p>\r\n");
      out.write("            <button class=\"btn\">veiw</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"images/D.jpeg\" alt=\"Spark Plug\">\r\n");
      out.write("            <h3>Engine 234</h3>\r\n");
      out.write("            <p>Part No: 1141876278</p>\r\n");
      out.write("            <p class=\"price\">$8.75</p>\r\n");
      out.write("            <button class=\"btn\">veiw</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Second Row -->\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"images/E.jpeg\" alt=\"Fuel Pump\">\r\n");
      out.write("            <h3>Engine 653</h3>\r\n");
      out.write("            <p>Part No: 10929284732</p>\r\n");
      out.write("            <p class=\"price\">$120.00</p>\r\n");
      out.write("            <button class=\"btn\">veiw</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"images/f.jpeg\" alt=\"Exhaust System\">\r\n");
      out.write("            <h3>Engine 352<h3>\r\n");
      out.write("            <p>Part No: 15394872923</p>\r\n");
      out.write("            <p class=\"price\">$250.50</p>\r\n");
      out.write("            <button class=\"btn\">veiw</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"images/g.jpeg\" alt=\"Radiator\">\r\n");
      out.write("            <h3>Engine 876</h3>\r\n");
      out.write("            <p>Part No: 13487429384</p>\r\n");
      out.write("            <p class=\"price\">$90.99</p>\r\n");
      out.write("            <button class=\"btn\">veiw</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <img src=\"images/h.jpeg\" alt=\"Battery\">\r\n");
      out.write("            <h3>Engine 324</h3>\r\n");
      out.write("            <p>Part No: 10429387483</p>\r\n");
      out.write("            <p class=\"price\">$70.00</p>\r\n");
      out.write("            <button class=\"btn\">veiw</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
